[window]
decorations = "none"
opacity = 0.97

[font]
size = 11.0

[colors.primary]
background = "#191414"
foreground = "#FFEAF2"

[colors.normal]
black   = "#191414"
red     = "#F1396D"
green   = "#D93665"
yellow  = "#FFB3CA"
blue    = "#FF6F9B"
magenta = "#F1396D"
cyan    = "#F88AB0"
white   = "#FFEAF2"

[colors.bright]
black   = "#2A2025"
red     = "#FF4D80"
green   = "#F4618E"
yellow  = "#FFD1DF"
blue    = "#FF7AA3"
magenta = "#FF5F91"
cyan    = "#FFEAF2"
white   = "#FFEAF2"


[colors.selection]
background = "#3A1F29"
text = "#FFEAF2"
