accent = "#F1396D"
cursor = "#F1396D"
foreground = "#FFEAF2"
background = "#191414"
selection_foreground = "#FFEAF2"
selection_background = "#3A1F29"

color0 = "#191414"
color1 = "#F1396D"
color2 = "#D93665"
color3 = "#FFB3CA"
color4 = "#FF6F9B"
color5 = "#F1396D"
color6 = "#F88AB0"
color7 = "#FFEAF2"

color8 = "#2A2025"
color9 = "#FF4D80"
color10 = "#F4618E"
color11 = "#FFD1DF"
color12 = "#FF7AA3"
color13 = "#FF5F91"
color14 = "#FFEAF2"
color15 = "#FFEAF2"
