# Hyprland Red Monarch Theme
# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

$activeBorderColor = rgba(F1396Dff)
$inactiveBorderColor = rgba(2A202588)
$groupBorderColor = rgba(F1396Ddd)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
    gaps_in = 3
    gaps_out = 8
    border_size = 2
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}

decoration {
    rounding = 8
    active_opacity = 0.98
    inactive_opacity = 0.94

    blur {
      enabled = yes
      size = 8
      passes = 2
      new_optimizations = true
      xray = false
    }

    shadow {
      enabled = yes
      render_power = 3
      range = 12
      color = rgba(F1396D33)
      color_inactive = rgba(19141455)
    }
}
