# Red Monarch Notification Theme
# Rose-black palette

text-color=#FFEAF2FF

border-color=#F1396DAA

background-color=#191414DD

progress-color=#F1396D99

default-timeout=4000
width=420
height=120
padding=16
margin=12
border-size=2
border-radius=8
outer-margin=10
anchor=top-right
layer=overlay
font=JetBrainsMono Nerd Font 11

[app-name=Spotify]
invisible=1

[mode=do-not-disturb]
invisible=true

[mode=do-not-disturb app-name=notify-send]
invisible=false
